package com.example.mobilenumberlocator;

import androidx.appcompat.app.AppCompatActivity;
import androidx.recyclerview.widget.LinearLayoutManager;
import androidx.recyclerview.widget.RecyclerView;

import android.os.Bundle;
import android.view.View;
import android.widget.ImageView;

import java.util.ArrayList;
import java.util.List;

public class STDCodes extends AppCompatActivity {

    RecyclerView recyclerView;
    ImageView back;
    SAdapter sAdapter;
    List<ModalStd> userList;
    LinearLayoutManager linearLayoutManager;


    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_stdcodes);

        recyclerView = findViewById(R.id.recyclerView);
        back = findViewById(R.id.back);

        back.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                onBackPressed();
            }
        });

        initData();
        initRecyclerView();
    }

    private void initData() {
        userList = new ArrayList<>();

        userList.add(new ModalStd("ABHAYAPURI" , "03669"));
        userList.add(new ModalStd("BAITHALANGSHU" , "03677"));
        userList.add(new ModalStd("BARAMA" , "03623"));
        userList.add(new ModalStd("BARPETA ROAD" , "03666"));
        userList.add(new ModalStd("BIHUPURIA" , "03759"));
        userList.add(new ModalStd("BIJNI" , "03668"));
        userList.add(new ModalStd("BILASIPARA" , "03667"));
        userList.add(new ModalStd("BOKAJAN" , "03675"));
        userList.add(new ModalStd("BOKAKHAT" , "03776"));
        userList.add(new ModalStd("BOKO" , "03621"));
        userList.add(new ModalStd("DHAKUAKHANA" , "03758"));
        userList.add(new ModalStd("DHEMAJI" , "03753"));
        userList.add(new ModalStd("DHUBRI" , "03662"));
        userList.add(new ModalStd("DIBRUGAR" , " 0373"));
        userList.add(new ModalStd("DIGBOI" , "03751"));
        userList.add(new ModalStd("DIPHU" , "03671"));
        userList.add(new ModalStd("GOALPARA" , "03663"));
        userList.add(new ModalStd("GOHPUR" , "03715"));
        userList.add(new ModalStd("GOLAGHAT" , "03774"));
        userList.add(new ModalStd("GUWAHAT" , " 0361"));
        userList.add(new ModalStd("HAILAKANDI" , "03844"));
        userList.add(new ModalStd("HAJO" , "03664"));
        userList.add(new ModalStd("HALFLONG" , "03673"));
        userList.add(new ModalStd("HOJAI" , "03674"));
        userList.add(new ModalStd("HOWRAGHAT" , "03676"));
        userList.add(new ModalStd("JORHA" , " 0376"));
        userList.add(new ModalStd("KARIMGANJ" , "03843"));
        userList.add(new ModalStd("KOKARAJHAR" , "03661"));
        userList.add(new ModalStd("MAIBONG" , "03670"));
        userList.add(new ModalStd("MAJULI" , "03775"));
        userList.add(new ModalStd("MANGALDOI" , "03713"));
        userList.add(new ModalStd("MARIANI" , "03771"));
        userList.add(new ModalStd("MORANHAT" , "03754"));
        userList.add(new ModalStd("MORIGAON" , "03678"));
        userList.add(new ModalStd("NAGAON" , "03672"));
        userList.add(new ModalStd("NALBARI" , "03624"));
        userList.add(new ModalStd("NORTH LAKHIMPUR" , "03752"));
        userList.add(new ModalStd("RANGAPARA" , "03714"));
        userList.add(new ModalStd("SADIYA" , "03756"));
        userList.add(new ModalStd("SIBSAGAR" , "03772"));
        userList.add(new ModalStd("SILCHAR" , "03842"));
        userList.add(new ModalStd("TARABARIHAT" , "03665"));
        userList.add(new ModalStd("TEZPUR" , "03712"));
        userList.add(new ModalStd("TINSUKI" , " 0374"));
        userList.add(new ModalStd("UDALGIRI" , "03711"));
        userList.add(new ModalStd("UDARBONDH" , "03841"));

                userList.add(new ModalStd("ADHAURA", "06180"));
                userList.add(new ModalStd("AMARPUR", "06420"));
                userList.add(new ModalStd("ARARIA", "06453"));
                userList.add(new ModalStd("ARERAJ", "06258"));
                userList.add(new ModalStd("ARRAH", "06182"));
                userList.add(new ModalStd("ARWAL", "06337"));
                userList.add(new ModalStd("AURANGABAD", "06186"));
                userList.add(new ModalStd("BAGAHA", "06251"));
                userList.add(new ModalStd("BANKA", "06424"));
                userList.add(new ModalStd("BANMANKHI", "06467"));
                userList.add(new ModalStd("BARACHAKIA", "06257"));
                userList.add(new ModalStd("BARAUNI", "06279"));
                userList.add(new ModalStd("BARH", "06132"));
                userList.add(new ModalStd("BAROSI", "06451"));
                userList.add(new ModalStd("BEGUSARAI", "06243"));
                userList.add(new ModalStd("BENIPATTI", "06271"));
                userList.add(new ModalStd("BENIPUR", "06242"));
                userList.add(new ModalStd("BETTIAH", "06254"));
                userList.add(new ModalStd("BHABHUA", "06189"));
                userList.add(new ModalStd("BHAGALPUR", "0641"));
                userList.add(new ModalStd("BIDUPUR", "06229"));
                userList.add(new ModalStd("BIHARSHARIF", "06112"));
                userList.add(new ModalStd("BIKRAM", "06135"));
                userList.add(new ModalStd("BIKRAMGANJ", "06185"));
                userList.add(new ModalStd("BIRPUR", "06471"));
                userList.add(new ModalStd("BUXER", "06183"));
                userList.add(new ModalStd("CHAKAI", "06347"));
                userList.add(new ModalStd("CHAPARA", "06152"));
                userList.add(new ModalStd("DALSINGHSARAI", "06278"));
                userList.add(new ModalStd("DANAPUR", "06115"));
                userList.add(new ModalStd("DARBHANGA", "06272"));
                userList.add(new ModalStd("DAUDNAGAR", "06328"));
                userList.add(new ModalStd("DHAKA", "06250"));
                userList.add(new ModalStd("DHAMDAHA", "06462"));
                userList.add(new ModalStd("DUMRAON", "06323"));
                userList.add(new ModalStd("EKMA", "06155"));
                userList.add(new ModalStd("FORBESGANJ", "06455"));
                userList.add(new ModalStd("GAYA", "0631"));
                userList.add(new ModalStd("GOGRI", "06245"));
                userList.add(new ModalStd("GOPALGANJ", "06156"));
                userList.add(new ModalStd("H.KHARAGPUR", "06342"));
                userList.add(new ModalStd("HAJIPUR", "06224"));
                userList.add(new ModalStd("HATHUA", "06150"));
                userList.add(new ModalStd("HILSA", "06111"));
                userList.add(new ModalStd("IMAMGANJ", "06331"));
        userList.add(new ModalStd("JAHANABAD", "06114"));
        userList.add(new ModalStd("JAINAGAR", "06246"));
        userList.add(new ModalStd("JAMUI", "06345"));
        userList.add(new ModalStd("JHAJHA", "06349"));
        userList.add(new ModalStd("JHANJHARPUR", "06273"));
        userList.add(new ModalStd("KAHALGAON", "06429"));
        userList.add(new ModalStd("KATIHAR", "06452"));
        userList.add(new ModalStd("KATORIA", "06425"));
        userList.add(new ModalStd("KHAGARIA", "06244"));
        userList.add(new ModalStd("KISHANGANJ", "06466"));
        userList.add(new ModalStd("KORHA", "06457"));
        userList.add(new ModalStd("LAKHISARAI", "06346"));
        userList.add(new ModalStd("MADHEPURA", "06476"));
        userList.add(new ModalStd("MADHUBANI", "06276"));
        userList.add(new ModalStd("MAHARAJGANJ", "06153"));
        userList.add(new ModalStd("MAHUA", "06227"));
        userList.add(new ModalStd("MAIRWA", "06157"));
        userList.add(new ModalStd("MALLEHPUR", "06348"));
        userList.add(new ModalStd("MASRAKH", "06159"));
        userList.add(new ModalStd("MOHANIA", "06187"));
        userList.add(new ModalStd("MONGHYR", "06344"));
        userList.add(new ModalStd("MOTIHARI", "06252"));
        userList.add(new ModalStd("MOTIPUR", "06223"));
        userList.add(new ModalStd("MUZAFFARPUR"," 0621"));
        userList.add(new ModalStd("NABINAGAR", "06332"));
        userList.add(new ModalStd("NARKATIAGANJ", "06253"));
        userList.add(new ModalStd("NAUGACHIA", "06421"));
        userList.add(new ModalStd("NAWADA", "06324"));
        userList.add(new ModalStd("PAKRIBARWAN", "06325"));
        userList.add(new ModalStd("PAKRIDAYAL", "06259"));
        userList.add(new ModalStd("PATNA"," 0612"));
        userList.add(new ModalStd("PHULPARAS", "06277"));
        userList.add(new ModalStd("PIRO", "06181"));
        userList.add(new ModalStd("PUPRI", "06228"));
        userList.add(new ModalStd("PURENA", "06454"));
        userList.add(new ModalStd("RAFIGANJ", "06327"));
        userList.add(new ModalStd("RAJAULI", "06336"));
        userList.add(new ModalStd("RAMNAGAR", "06256"));
        userList.add(new ModalStd("RANIGANJ", "06461"));
        userList.add(new ModalStd("RAXAUL", "06255"));
        userList.add(new ModalStd("ROHTAS", "06188"));
        userList.add(new ModalStd("ROSERA", "06275"));
        userList.add(new ModalStd("S.BAKHTIARPUR", "06475"));
        userList.add(new ModalStd("SAHARSA", "06478"));
        userList.add(new ModalStd("SAMASTIPUR", "06274"));
        userList.add(new ModalStd("SASARAM", "06184"));
        userList.add(new ModalStd("SEIKHPURA", "06341"));
        userList.add(new ModalStd("SHEOHAR", "06222"));
        userList.add(new ModalStd("SHERGHATI", "06326"));
        userList.add(new ModalStd("SIDHAWALIA", "06151"));
        userList.add(new ModalStd("SINGHWARA", "06247"));
        userList.add(new ModalStd("SITAMARHI", "06226"));
        userList.add(new ModalStd("SIWAN", "06154"));
        userList.add(new ModalStd("SONEPUR", "06158"));
        userList.add(new ModalStd("SUPAUL", "06473"));
        userList.add(new ModalStd("THAKURGANJ", "06459"));
        userList.add(new ModalStd("TRIVENIGANJ", "06477"));
        userList.add(new ModalStd("UDAKISHANGANJ", "06479"));
        userList.add(new ModalStd("WAZIRGANJ", "06322"));

                userList.add(new ModalStd("AHMEDABAD" ," 079"));
                userList.add(new ModalStd("AHWA" ,"02631"));
                userList.add(new ModalStd("AMOD" ,"02641"));
                userList.add(new ModalStd("AMRELI" ,"02792"));
                userList.add(new ModalStd("ANAND" ,"02692"));
                userList.add(new ModalStd("ANJAR" ,"02836"));
                userList.add(new ModalStd("ANKALESHWAR" ,"02646"));
                userList.add(new ModalStd("BABRA" ,"02791"));
                userList.add(new ModalStd("BALASINOR" ,"02690"));
                userList.add(new ModalStd("BANSADA" ,"02630"));
                userList.add(new ModalStd("BARDOLI" ,"02622"));
                userList.add(new ModalStd("BAREJA" ,"02718"));
                userList.add(new ModalStd("BARWALA" ,"02711"));
                userList.add(new ModalStd("BAYAD" ,"02779"));
                userList.add(new ModalStd("BHACHAV" ,"02837"));
                userList.add(new ModalStd("BHANVAD" ,"02896"));
                userList.add(new ModalStd("BHARUCH" ,"02642"));
                userList.add(new ModalStd("BHAVNAGAR"," 0278"));
                userList.add(new ModalStd("BHILODA" ,"02771"));
                userList.add(new ModalStd("BHUJ" ,"02832"));
                userList.add(new ModalStd("BILLIMORA" ,"02634"));
                userList.add(new ModalStd("BORSAD" ,"02696"));
                userList.add(new ModalStd("BOTAD" ,"02849"));
                userList.add(new ModalStd("CHANASMA" ,"02734"));
                userList.add(new ModalStd("CHHOTA UDAIPUR" ,"02669"));
                userList.add(new ModalStd("CHOTILA" ,"02751"));
                userList.add(new ModalStd("DABHOI" ,"02663"));
                userList.add(new ModalStd("DAHOD" ,"02673"));
                userList.add(new ModalStd("DAMNAGAR" ,"02793"));
                userList.add(new ModalStd("DANTA" ,"02749"));
                userList.add(new ModalStd("DASADA" ,"02757"));
                userList.add(new ModalStd("DEDIAPADA" ,"02649"));
                userList.add(new ModalStd("DEESA" ,"02744"));
                userList.add(new ModalStd("DEHGAM" ,"02716"));
                userList.add(new ModalStd("DEODAR" ,"02735"));
                userList.add(new ModalStd("DEVGADHBARIA" ,"02678"));
                userList.add(new ModalStd("DHANDHUKA" ,"02713"));
                userList.add(new ModalStd("DHANERA" ,"02748"));
                userList.add(new ModalStd("DHARAMPUR" ,"02633"));
                userList.add(new ModalStd("DHARI" ,"02797"));
                userList.add(new ModalStd("DHOLKA" ,"02714"));
                userList.add(new ModalStd("DHORAJI" ,"02824"));
                userList.add(new ModalStd("DHRANGADHRA" ,"02754"));
                userList.add(new ModalStd("DHROL" ,"02897"));
                userList.add(new ModalStd("FORTSONGADH" ,"02624"));
                userList.add(new ModalStd("GADHADA" ,"02847"));
                userList.add(new ModalStd("GANDHI NAGAR" ,"02712"));
                userList.add(new ModalStd("GARIADHAR" ,"02843"));
                userList.add(new ModalStd("GODHRA" ,"02672"));
                userList.add(new ModalStd("GOGODAR" ,"02806"));
                userList.add(new ModalStd("GONDAL" ,"02825"));
                userList.add(new ModalStd("HALOL" ,"02676"));
                userList.add(new ModalStd("HALVAD" ,"02758"));
                userList.add(new ModalStd("HARIJ" ,"02733"));
                userList.add(new ModalStd("HIMATNAGAR" ,"02772"));
                userList.add(new ModalStd("IDAR" ,"02778"));
                userList.add(new ModalStd("JAMBUSAR" ,"02644"));
                userList.add(new ModalStd("JAMJODHPUR" ,"02898"));
                userList.add(new ModalStd("JAMKALYANPUR" ,"02891"));
                userList.add(new ModalStd("JAMNAGAR"," 0288"));
                userList.add(new ModalStd("JASDAN"," 02821"));
                userList.add(new ModalStd("JETPUR"," 02823"));
                userList.add(new ModalStd("JHAGADIA"," 02645"));
                userList.add(new ModalStd("JHALOD"," 02679"));
                userList.add(new ModalStd("JODIA"," 02893"));
                userList.add(new ModalStd("JUNAGAR","H 0285"));
                userList.add(new ModalStd("KALAWAD"," 02894"));
                userList.add(new ModalStd("KALOL"," 02764"));
                userList.add(new ModalStd("KAPAD WANJ"," 02691"));
                userList.add(new ModalStd("KESHOD"," 02871"));
                userList.add(new ModalStd("KHAMBAT"," 02698"));
                userList.add(new ModalStd("KHAMBHALIA"," 02833"));
                userList.add(new ModalStd("KHAVDA"," 02803"));
                userList.add(new ModalStd("KHEDBRAHMA"," 02775"));
                userList.add(new ModalStd("KHERALU"," 02761"));
                userList.add(new ModalStd("KODINAR"," 02795"));
                userList.add(new ModalStd("KOTDASANGHANI"," 02827"));
                userList.add(new ModalStd("KUNKAWAV"," 02796"));
                userList.add(new ModalStd("KUTCHMANDVI"," 02834"));
                userList.add(new ModalStd("KUTIYANA"," 02804"));
                userList.add(new ModalStd("LAKHPAT"," 02839"));
                userList.add(new ModalStd("LAKHTAR"," 02759"));
                userList.add(new ModalStd("LALPUR"," 02895"));
                userList.add(new ModalStd("LIMBDI"," 02753"));
                userList.add(new ModalStd("LIMKHEDA"," 02677"));
                userList.add(new ModalStd("LUNAVADA"," 02674"));
                userList.add(new ModalStd("M.M.MANGROL"," 02629"));
                userList.add(new ModalStd("MAHUVA"," 02844"));
                userList.add(new ModalStd("MALIA-HATINA"," 02870"));
                userList.add(new ModalStd("MALIYA MIYANA"," 02829"));
                userList.add(new ModalStd("MALPUR"," 02773"));
                userList.add(new ModalStd("MANAVADAR"," 02874"));
                userList.add(new ModalStd("MANDVI"," 02623"));
                userList.add(new ModalStd("MANGROL"," 02878"));
                userList.add(new ModalStd("MEHMEDABAD"," 02694"));
                userList.add(new ModalStd("MEHSANA"," 02762"));
                userList.add(new ModalStd("MIYAGAM"," 02666"));
                userList.add(new ModalStd("MODASA"," 02774"));
                userList.add(new ModalStd("MORVI"," 02822"));
                userList.add(new ModalStd("MULI"," 02756"));
                userList.add(new ModalStd("MUNDRA"," 02838"));
                userList.add(new ModalStd("NADIA","D 0268"));
                userList.add(new ModalStd("NAKHATRANA"," 02835"));
                userList.add(new ModalStd("NALIA"," 02831"));
                userList.add(new ModalStd("NASWADI"," 02661"));
                userList.add(new ModalStd("NAVASARI"," 02637"));
                userList.add(new ModalStd("NIZAR"," 02628"));
                userList.add(new ModalStd("OKHA"," 02892"));
                userList.add(new ModalStd("PADDHARI"," 02820"));
                userList.add(new ModalStd("PADRA"," 02662"));
                userList.add(new ModalStd("PALANPUR"," 02742"));
                userList.add(new ModalStd("PALITANA"," 02848"));
                userList.add(new ModalStd("PATAN"," 02766"));
                userList.add(new ModalStd("PAVIJETPUR"," 02664"));
                userList.add(new ModalStd("PORBANDE","R 0286"));
                userList.add(new ModalStd("PRANTIJ"," 02770"));
                userList.add(new ModalStd("RADHANPUR"," 02746"));
                userList.add(new ModalStd("RAHPAR"," 02830"));
                userList.add(new ModalStd("RAJAULA"," 02794"));
                userList.add(new ModalStd("RAJKO","T 0281"));
                userList.add(new ModalStd("RAJPIPLA"," 02640"));
                userList.add(new ModalStd("RANAVAV"," 02801"));
                userList.add(new ModalStd("SANAND"," 02717"));
                userList.add(new ModalStd("SANKHEDA"," 02665"));
                userList.add(new ModalStd("SANTALPUR"," 02738"));
                userList.add(new ModalStd("SANTRAMPUR"," 02675"));
                userList.add(new ModalStd("SAVARKUNDLA"," 02845"));
                userList.add(new ModalStd("SAVLI"," 02667"));
                userList.add(new ModalStd("SAYAN"," 02621"));
                userList.add(new ModalStd("SAYLA"," 02755"));
                userList.add(new ModalStd("SHEHRA"," 02670"));
                userList.add(new ModalStd("SIDHPUR"," 02767"));
                userList.add(new ModalStd("SIHOR"," 02846"));
                userList.add(new ModalStd("SOJITRA"," 02697"));
                userList.add(new ModalStd("SUMRASAR"," 02808"));
                userList.add(new ModalStd("SURA","T 0261"));
                userList.add(new ModalStd("SURENDRANAGAR"," 02752"));
                userList.add(new ModalStd("TALAJA"," 02842"));
                userList.add(new ModalStd("TALALA"," 02877"));
                userList.add(new ModalStd("THARA"," 02747"));
                userList.add(new ModalStd("THARAD"," 02737"));
                userList.add(new ModalStd("THASRA"," 02699"));
                userList.add(new ModalStd("UNA-DIU"," 02875"));
                userList.add(new ModalStd("UPLETA"," 02826"));
                userList.add(new ModalStd("VADGAM"," 02739"));
                userList.add(new ModalStd("VADODAR","A 0265"));
                userList.add(new ModalStd("VALIA 02VANTHALI"," 02872"));
                userList.add(new ModalStd("VAP","I 0260"));
                userList.add(new ModalStd("VAV"," 02740"));
                userList.add(new ModalStd("VERAVAL"," 02876"));
                userList.add(new ModalStd("VIJAPUR"," 02763"));
                userList.add(new ModalStd("VIRAMGAM"," 02715"));
                userList.add(new ModalStd("VISAVADAR"," 02873"));
                userList.add(new ModalStd("VISNAGAR"," 02765"));
                userList.add(new ModalStd("VYARA"," 02626"));
                userList.add(new ModalStd("WAGHODIA"," 02668"));
                userList.add(new ModalStd("WANKANER"," 02828"));
                userList.add(new ModalStd("VALOD"," 02625"));
                userList.add(new ModalStd("VALSAD"," 02632"));

        userList.add(new ModalStd("ADAMPUR MANDI", "01669"));
        userList.add(new ModalStd("AMBALA", "0171"));
        userList.add(new ModalStd("ASSANDH", "01749"));
        userList.add(new ModalStd("BAHADURGARH", "01276"));
        userList.add(new ModalStd("BARARA", "01731"));
        userList.add(new ModalStd("BARWALA", "01693"));
        userList.add(new ModalStd("BAWAL", "01284"));
        userList.add(new ModalStd("BAWANIKHERA", "01254"));
        userList.add(new ModalStd("BHIWANI", "01664"));
        userList.add(new ModalStd("CHARKHIDADRI", "01250"));
        userList.add(new ModalStd("CHEEKA", "01743"));
        userList.add(new ModalStd("CHHACHRAULI", "01735"));
        userList.add(new ModalStd("DABWALI", "01668"));
        userList.add(new ModalStd("ELLENABAD", "01698"));
        userList.add(new ModalStd("FARIDABAD", "0129"));
        userList.add(new ModalStd("FATEHABAD", "01667"));
        userList.add(new ModalStd("FEROJPUR JHIRKA", "01268"));
        userList.add(new ModalStd("GHARAUNDA", "01748"));
        userList.add(new ModalStd("GOHANA", "01263"));
        userList.add(new ModalStd("GURGAON", "0124"));
        userList.add(new ModalStd("HANSI", "01663"));
        userList.add(new ModalStd("HISSAR", "01662"));
        userList.add(new ModalStd("JAGADHARI", "01732"));
        userList.add(new ModalStd("JATUSANA", "01281"));
        userList.add(new ModalStd("JHAJJAR", "01251"));
        userList.add(new ModalStd("JIND", "01681"));
        userList.add(new ModalStd("JULANA", "01683"));
        userList.add(new ModalStd("KAITHAL", "01746"));
        userList.add(new ModalStd("KALANAUR", "01258"));
        userList.add(new ModalStd("KALANWALI", "01696"));
        userList.add(new ModalStd("KALKA", "01733"));
        userList.add(new ModalStd("KARNAL", "0184"));
        userList.add(new ModalStd("KOSLI", "01259"));
        userList.add(new ModalStd("KURUKSHETRA", "01744"));
        userList.add(new ModalStd("LOHARU", "01252"));
        userList.add(new ModalStd("MEHAM", "01257"));
        userList.add(new ModalStd("MOHINDERGARH", "01285"));
        userList.add(new ModalStd("NARAINGARH", "01734"));
        userList.add(new ModalStd("NARNAUL", "01282"));
        userList.add(new ModalStd("NARWANA", "01684"));
        userList.add(new ModalStd("NILOKHERI", "01745"));
        userList.add(new ModalStd("NUH", "01267"));
        userList.add(new ModalStd("PALWAL", "01275"));
        userList.add(new ModalStd("PANIPAT", "0180"));
        userList.add(new ModalStd("PEHOWA", "01741"));
        userList.add(new ModalStd("RATIA", "01697"));
        userList.add(new ModalStd("REWARI", "01274"));
        userList.add(new ModalStd("ROHTAK", "01262"));
        userList.add(new ModalStd("SAFIDON", "01686"));
        userList.add(new ModalStd("SIRSA", "01666"));
        userList.add(new ModalStd("SIWANI", "01255"));
        userList.add(new ModalStd("SONIPAT", "0130"));
        userList.add(new ModalStd("TOHANA", "01692"));
        userList.add(new ModalStd("TOHSAM", "01253"));


                userList.add(new ModalStd("AMB ","01976"));
                userList.add(new ModalStd("ARKI ","01796"));
                userList.add(new ModalStd("BANJAR ","01903"));
                userList.add(new ModalStd("BHARMOUR ","01895"));
                userList.add(new ModalStd("BILASPUR ","01978"));
                userList.add(new ModalStd("CHAMBA ","01899"));
                userList.add(new ModalStd("CHURAH ","01896"));
                userList.add(new ModalStd("DEHRA GOPIPUR ","01970"));
                userList.add(new ModalStd("HAMIRPUR ","01972"));
                userList.add(new ModalStd("JOGINDERNAGAR ","01908"));
                userList.add(new ModalStd("KALPA ","01786"));
                userList.add(new ModalStd("KANGRA ","01892"));
                userList.add(new ModalStd("KULLU ","01902"));
                userList.add(new ModalStd("LAHUL ","01900"));
                userList.add(new ModalStd("MANDI ","01905"));
                userList.add(new ModalStd("NAHAN ","01702"));
                userList.add(new ModalStd("NALAGARH ","01795"));
                userList.add(new ModalStd("NIRMAND ","01904"));
                userList.add(new ModalStd("NURPUR ","01893"));
                userList.add(new ModalStd("PALAMPUR ","01894"));
                userList.add(new ModalStd("PANGI ","01897"));
                userList.add(new ModalStd("PAONTA ","01704"));
                userList.add(new ModalStd("POOH ","01785"));
                userList.add(new ModalStd("RAJGARH ","01799"));
                userList.add(new ModalStd("RAMPUR BUSHAHAR ","01782"));
                userList.add(new ModalStd("ROHRU ","01781"));
                userList.add(new ModalStd("SHIMLA"," 0177"));
                userList.add(new ModalStd("SOLAN ","01792"));
                userList.add(new ModalStd("SPITI ","01906"));
                userList.add(new ModalStd("SUNDERNAGAR ","01907"));
                userList.add(new ModalStd("THEOG ","01783"));
                userList.add(new ModalStd("UDAIPUR ","01909"));
                userList.add(new ModalStd("UNA","01975"));

                userList.add(new ModalStd("AKHNOOR ","01924"));
                userList.add(new ModalStd("ANANTNAG ","01932"));
                userList.add(new ModalStd("BADGAM ","01951"));
                userList.add(new ModalStd("BANDIPUR ","01957"));
                userList.add(new ModalStd("BARAMULLA ","01952"));
                userList.add(new ModalStd("BASHOLI ","01921"));
                userList.add(new ModalStd("BEDARWAH ","01997"));
                userList.add(new ModalStd("DODA ","01996"));
                userList.add(new ModalStd("JAMMU"," 0191"));
                userList.add(new ModalStd("KALAKOT ","01964"));
                userList.add(new ModalStd("KARGIL ","01985"));
                userList.add(new ModalStd("KARNAH ","01958"));
                userList.add(new ModalStd("KATHUA ","01922"));
                userList.add(new ModalStd("KISHTWAR ","01995"));
                userList.add(new ModalStd("KULGAM ","01931"));
                userList.add(new ModalStd("KUPWARA ","01955"));
                userList.add(new ModalStd("LEH ","01982"));
                userList.add(new ModalStd("MAHORE ","01999"));
                userList.add(new ModalStd("NOBRA ","01980"));
                userList.add(new ModalStd("NOWSHERA ","01960"));
                userList.add(new ModalStd("NYOMA ","01981"));
                userList.add(new ModalStd("PADAM ","01983"));
                userList.add(new ModalStd("PAHALGAM ","01936"));
                userList.add(new ModalStd("POONCH ","01965"));
                userList.add(new ModalStd("PULWAMA ","01933"));
                userList.add(new ModalStd("RAJOURI ","01962"));
                userList.add(new ModalStd("RAMBAN ","01998"));
                userList.add(new ModalStd("RAMNAGAR ","01990"));
                userList.add(new ModalStd("REASI ","01991"));
                userList.add(new ModalStd("SAMBA ","01923"));
                userList.add(new ModalStd("SOPORE ","01954"));
                userList.add(new ModalStd("SRINAGAR"," 0194"));
                userList.add(new ModalStd("UDHAMPUR ","01992"));
                userList.add(new ModalStd("URI ","01956"));

    }
    private void initRecyclerView() {

        recyclerView=findViewById(R.id.recyclerView);
        linearLayoutManager = new LinearLayoutManager(this);
        linearLayoutManager.setOrientation(RecyclerView.VERTICAL);
        recyclerView.setLayoutManager(linearLayoutManager);
        sAdapter = new SAdapter(userList,getApplicationContext());
        recyclerView.setAdapter(sAdapter);
        sAdapter.notifyDataSetChanged();

    }
}